### ISSUE TITLE
can it be used on ARM64

### ISSUE THREAD

**Issue by siddontang** [tikv/crc64fast#2]
TiKV will be heavily used on ARM64, so maybe we should also consider ARM acceleration. Refer to https://github.com/facebook/rocksdb/blob/master/util/crc32c_arm64.h.

**Comment by siddontang** [comment]
seem  crc32fast has already supported ARAM : https://github.com/srijs/rust-crc32fast/blob/master/src/specialized/aarch64.rs

**Comment by kennytm** [comment]
Yes, we do plan to support AArch64. We should be able to reuse the same algorithm for x86_64 using the [polynomial multiplication instructions](https://stackoverflow.com/questions/54048837/how-to-perform-polynomial-multiplication-using-arm64) (but we may either need to use `asm!` or [extend Rust's AArch64 intrinsics](https://doc.rust-lang.org/core/arch/aarch64/index.html)).

(CRC32 is different. There is a dedicated instruction to compute CRC32 and CRC32c on ARM, not for CRC64.)

Meanwhile, the table-based non-SIMD algorithm is platform-agnostic, so this package itself can work on any architectures.
