### ISSUE TITLE
Wrong CRC algorithm mentioned in crate documentation

### ISSUE THREAD

**Issue by malaire** [tikv/crc64fast#5]
This crate computes `CRC-64/XZ` and not `CRC-64/ECMA` as documentation says. (`CRC-64/XZ` is often misidentified as `CRC-64/ECMA`.)

You can see their differences e.g. at [Catalogue of parametrised CRC algorithms](https://reveng.sourceforge.io/crc-catalogue/all.htm).

For example ECMA starts with value 0 while `CRC-64/XZ` starts with `!0` and this crate clearly uses `!0` at
https://github.com/tikv/crc64fast/blob/baedd67eedec13ae10d523232c5a3c58ede48e16/src/lib.rs#L46

**Comment by kennytm** [comment]
Thanks for noticing. This was called "ECMA" because both Golang and `crc v1.x.x` said so :sweat_smile: 

reworded in #10
